import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
            'resources/sass/app.scss',
            'resources/js/app.js',
            'resources/css/app.css', 
            "resources/Adminkit/bootstrap/css/bootstrap.css",
            "resources/Adminkit/bootstrap/css/responsive.css",
            "resources/Adminkit/theme/css/glyphicons.css",
            "resources/Adminkit/theme/scripts/plugins/forms/pixelmatrix-uniform/css/uniform.default.css",
            "resources/Adminkit/theme/scripts/plugins/other/excanvas/excanvas.js",
            "resources/Adminkit/bootstrap/extend/jasny-bootstrap/css/jasny-bootstrap.min.css",
            "resources/Adminkit/bootstrap/extend/jasny-bootstrap/css/jasny-bootstrap-responsive.min.css",
            "resources/Adminkit/bootstrap/extend/bootstrap-wysihtml5/css/bootstrap-wysihtml5-0.0.2.css",
            "resources/Adminkit/bootstrap/extend/bootstrap-select/bootstrap-select.css",
            "resources/Adminkit/bootstrap/extend/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
            "resources/Adminkit/theme/scripts/plugins/forms/select2/select2.css",
            "resources/Adminkit/theme/scripts/plugins/forms/bootstrap-datetimepicker/css/datetimepicker.css",
            "resources/Adminkit/theme/scripts/plugins/system/jquery-ui/css/smoothness/jquery-ui-1.9.2.custom.min.css",
            "resources/Adminkit/theme/scripts/plugins/color/jquery-miniColors/jquery.miniColors.css",
            "resources/Adminkit/theme/scripts/plugins/notifications/notyfy/jquery.notyfy.css",
            "resources/Adminkit/theme/scripts/plugins/notifications/notyfy/themes/default.css",
            "resources/Adminkit/theme/scripts/plugins/notifications/Gritter/css/jquery.gritter.css",
            "resources/Adminkit/theme/scripts/plugins/charts/easy-pie/jquery.easy-pie-chart.css",
            "resources/Adminkit/theme/scripts/plugins/other/google-code-prettify/prettify.css",
            "resources/Adminkit/bootstrap/extend/bootstrap-image-gallery/css/bootstrap-image-gallery.min.css",
            "resources/Adminkit/theme/css/style.min.css",
            "resources/Adminkit/theme/scripts/plugins/system/less.min.js",
            "resources/themes/bws/css/vendor.min.css" ,
            "resources/themes/bws/css/theme-core.css" ,
            "resources/themes/bws/css/module-essentials.min.css" ,
            "resources/themes/bws/css/module-material.min.css" ,
            "resources/themes/bws/css/module-layout.min.css" ,
            "resources/themes/bws/css/module-sidebar.min.css" ,
            "resources/themes/bws/css/module-sidebar-skins.min.css" ,
            "resources/themes/bws/css/module-navbar.min.css" ,
            "resources/themes/bws/css/module-messages.min.css" ,
            "resources/themes/bws/css/module-carousel-slick.min.css" ,
            "resources/themes/bws/css/module-charts.min.css" ,
            "resources/themes/bws/css/module-maps.min.css" ,
            "resources/themes/bws/css/module-colors-alerts.min.css" ,
            "resources/themes/bws/css/module-colors-background.min.css" ,
            "resources/themes/bws/css/module-colors-buttons.min.css" ,
            "resources/themes/bws/css/module-colors-text.min.css" ,
            "resources/themes/bws/css/font-style.css" ,
            "resources/themes/bws/css/custom-font.css",
            "resources/themes/bws/layerslider/css/layerslider.css",
            "resources/themes/bws/css/style.css",
            "resources/themes/bws/js/vendor-core.min.js",
            "resources/themes/bws/js/vendor-countdown.min.js",
            "resources/themes/bws/js/vendor-tables.min.js",
            "resources/themes/bws/js/vendor-forms.min.js",
            "resources/themes/bws/js/vendor-carousel-slick.min.js",
            "resources/themes/bws/js/vendor-player.min.js",
            "resources/themes/bws/js/vendor-charts-flot.min.js",
            "resources/themes/bws/js/vendor-nestable.min.js",
            "resources/themes/bws/js/module-essentials.min.js",
            "resources/themes/bws/js/module-material.min.js",
            "resources/themes/bws/js/module-layout.min.js",
            "resources/themes/bws/js/module-sidebar.min.js",
            "resources/themes/bws/js/module-carousel-slick.min.js",
            "resources/themes/bws/js/module-player.min.js",
            "resources/themes/bws/js/module-messages.min.js",
            "resources/themes/bws/js/module-maps-google.min.js",
            "resources/themes/bws/js/module-charts-flot.min.js",
            "resources/themes/bws/layerslider/js/greensock.js",
            "resources/themes/bws/layerslider/js/layerslider.transitions.js", 
            "resources/themes/bws/layerslider/js/layerslider.kreaturamedia.jquery.js" 
            ],
            refresh: true,
        }),
    ],
});
